/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package prtpvtienda;

import Articulos.Articulo;
import Ofertas.PanelOfertas;
import bd.bd;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronal Arrayaza DAM1C
 */
public class PanelOfertasCliente extends javax.swing.JDialog {

    /**
     * Creates new form PanelOfertasCliente
     * @param Usuario usu:
     */
    public PanelOfertasCliente(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        // this.setSize(this.getToolkit().getScreenSize());

        cargarIMG("/Imagenes/familia.png", this.btHome);
        cargarIMG("/Imagenes/familia.png", this.btPerfil);        
        cargarIMG("/Imagenes/oferta.png", this.btPedidos);
        cargarIMG("/Imagenes/carrito2.png", this.btPedidos);

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/pedido.png"));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(35, 35, Image.SCALE_DEFAULT));
        this.btOfertas.setIcon(icono);
    }

    private void cargarIMG(String url, JButton boton) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(35, 35, Image.SCALE_DEFAULT));
        boton.setIcon(icono);

        boton.setIconTextGap(2);
        boton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        boton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

    }

    public void cargarOfertas() {

    }

    public String cargarFiltros() {
        String sql = "";
        if (this.txtOfertas.getText().length() > 0) {

            //select * from articulos a, aplican n WHERE n.ofertasId=29 and a.ref=n.articulosRef and (a.ref like '%REF%' or a.descripcion like '%REF%');
            if (this.txtArticulos.getText().length() > 0) {
                sql = "select * from articulos a, aplican n WHERE n.ofertasId=" + this.txtOfertas.getText() + " and a.ref=n.articulosRef ";
            } else {
                sql = "select * from articulos a, aplican n WHERE n.ofertasId=" + this.txtOfertas.getText()
                        + " and a.ref=n.articulosRef and (a.ref like '%" + this.txtArticulos.getText()
                        + "%' or a.descripcion like '%" + this.txtArticulos.getText() + "%')";
            }
        } else {

            if (this.txtArticulos.getText().length() > 0) {
                sql = "select * from articulos where ref like '%" + this.txtArticulos + "%' or ref like '%" + this.txtArticulos + "%'";
            } else {
                sql = "select * from articulos";
            }

        }
        return sql;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        btHome = new javax.swing.JButton();
        btPerfil = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        btPedidos = new javax.swing.JButton();
        btCesto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtArticulos = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btOfertas = new javax.swing.JButton();
        lDescricpcion = new javax.swing.JLabel();
        txtOfertas = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        pnVisor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("ADMINISTRATIVO");
        jToolBar1.add(jLabel1);

        btHome.setText("HOME");
        btHome.setFocusable(false);
        btHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btHome.setMaximumSize(new java.awt.Dimension(120, 45));
        btHome.setMinimumSize(new java.awt.Dimension(120, 45));
        btHome.setPreferredSize(new java.awt.Dimension(120, 45));
        btHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btHome);

        btPerfil.setText("PERFIL");
        btPerfil.setFocusable(false);
        btPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPerfil.setMaximumSize(new java.awt.Dimension(120, 45));
        btPerfil.setMinimumSize(new java.awt.Dimension(120, 45));
        btPerfil.setPreferredSize(new java.awt.Dimension(120, 45));
        btPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btPerfil);
        jToolBar1.add(jSeparator1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("OPERACIONES");
        jLabel2.setToolTipText("OPERACIONES");
        jToolBar1.add(jLabel2);

        btPedidos.setText("PEDIDOS");
        btPedidos.setFocusable(false);
        btPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPedidos.setMaximumSize(new java.awt.Dimension(120, 45));
        btPedidos.setMinimumSize(new java.awt.Dimension(120, 45));
        btPedidos.setPreferredSize(new java.awt.Dimension(120, 45));
        btPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btPedidos);

        btCesto.setText("CESTA");
        btCesto.setFocusable(false);
        btCesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCesto.setMaximumSize(new java.awt.Dimension(120, 45));
        btCesto.setMinimumSize(new java.awt.Dimension(120, 45));
        btCesto.setPreferredSize(new java.awt.Dimension(120, 45));
        btCesto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btCesto);

        jLabel3.setText("OFERTAS DISPONIBLES:");

        jLabel4.setText("ARTICULOS:");

        btBuscar.setText("Busar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btOfertas.setMaximumSize(new java.awt.Dimension(40, 40));
        btOfertas.setMinimumSize(new java.awt.Dimension(40, 40));
        btOfertas.setPreferredSize(new java.awt.Dimension(40, 40));
        btOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOfertasActionPerformed(evt);
            }
        });

        lDescricpcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lDescricpcion.setText("jLabel6");

        txtOfertas.setText("jTextField1");

        pnVisor.setAutoscrolls(true);
        pnVisor.setMinimumSize(new java.awt.Dimension(300, 300));
        pnVisor.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout pnVisorLayout = new javax.swing.GroupLayout(pnVisor);
        pnVisor.setLayout(pnVisorLayout);
        pnVisorLayout.setHorizontalGroup(
            pnVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnVisorLayout.setVerticalGroup(
            pnVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        scroll.setViewportView(pnVisor);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btBuscar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lDescricpcion, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scroll)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscar)))
                    .addComponent(btOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDescricpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String sql = this.cargarFiltros();
        /*
        [200, 250]
         */
        int xPanel = this.pnVisor.getSize().width;
        int yPanel = this.pnVisor.getSize().height;
        this.pnVisor.removeAll();
        int y = 0;
        int x = 0;
        try {
            ResultSet rs = bd.Consulta(sql);
            while (rs.next()) {
                String refe = rs.getString("ref");
                double dto = 0;
                try {
                    dto = rs.getDouble("descuento");
                } catch (Exception ex) {

                }
                int cantidad = 0;
                try {
                    cantidad = rs.getInt("cantidad");
                } catch (Exception ex) {
                    
                }
                Articulo arti = new Articulo(refe);
                arti.recuperaDatos();
                Muestra muestra = new Muestra(arti,"01", dto, cantidad);
                muestra.setSize(200, 250);
                muestra.setLocation(x, y);
                this.pnVisor.add(muestra, BorderLayout.LINE_END);
                this.pnVisor.revalidate();
                this.pnVisor.repaint();
                if ((x + 405) > xPanel) {
                    x = 0;
                    y = y + 255;
                } else {
                    x = x + 205;
                }
            }
            if(yPanel<(y+255)){
                //this.pnVisor.setSize(new Dimension(xPanel, (y+255)));
                this.pnVisor.setPreferredSize(new Dimension(xPanel, (y+255)));
                this.scroll.updateUI();
            }
            else{
                
                this.pnVisor.setPreferredSize(this.scroll.getPreferredSize());
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOfertasActionPerformed
        PanelOfertas dialog = new PanelOfertas(true, new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                //System.exit(0);
            }
        });
        dialog.setVisible(true);
        if (dialog.getResult() == JOptionPane.OK_OPTION) {
            this.lDescricpcion.setText(dialog.getOfertas().getNombre());
            this.txtOfertas.setText(String.valueOf(dialog.getOfertas().getId()));
        }
    }//GEN-LAST:event_btOfertasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelOfertasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelOfertasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelOfertasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelOfertasCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PanelOfertasCliente dialog = new PanelOfertasCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCesto;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btOfertas;
    private javax.swing.JButton btPedidos;
    private javax.swing.JButton btPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lDescricpcion;
    private javax.swing.JPanel pnVisor;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField txtArticulos;
    private javax.swing.JTextField txtOfertas;
    // End of variables declaration//GEN-END:variables
}
