/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prtpvtienda;

import Articulos.Articulo;
import Ofertas.PanelOfertas;
import Pedidos.Interfaces.PanelCarrito;
import Pedidos.Interfaces.PanelPedido;
import Persona.Cliente;
import Persona.frPerfil;
import bd.Systema;
import bd.bd;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ronal Arrayaza DAM1C
 */
public class PanelOfertasCli extends javax.swing.JFrame {

    private Cliente cliente;

    /**
     * Creates new form PanelOfertasCli
     */
    public PanelOfertasCli(Cliente cli) {
        initComponents();
        this.cliente = cli;
        this.cargarPerfil();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cargarIcono("/Imagenes/perfil.png", this.btPerfil);
        cargarIcono("/Imagenes/lista.png", this.btPedidos);
        cargarIcono("/Imagenes/carrito2.png", this.btCesto);

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/lupa.png"));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(32, 32, Image.SCALE_DEFAULT));
        this.btOfertas.setIcon(icono);
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/tpv.png")).getImage());
    }

    private void cargarIcono(String url, JButton boton) {

        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(35, 35, Image.SCALE_DEFAULT));
        boton.setIcon(icono);

        boton.setIconTextGap(2);
        boton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        boton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

    }

    private void cargarPerfil() {
        this.lCorreoCli.setText(cliente.getCorreo());
        this.lNombre.setText(cliente.getApellidos() + ", " + cliente.getNombres());
        try {
            ImageIcon icon;
            if(cliente.getRutaImg().equals("predePer.png")){
                
                icon = new ImageIcon(getClass().getResource("/Imagenes/predePer.png"));
            }else{                
                icon = new ImageIcon(Systema.getRutaClientes() + cliente.getRutaImg());
            }
            

            ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(this.lbCliImg.getWidth(), this.lbCliImg.getHeight(), Image.SCALE_DEFAULT));
            this.lbCliImg.setIcon(icono);
        } catch (Exception ex) {

        }
    }

    public String cargarFiltros() {
        String sql = "";
        if (this.txtOfertas.getText().length() > 0) {

            //select * from articulos a, aplican n WHERE n.ofertasId=29 and a.ref=n.articulosRef and (a.ref like '%REF%' or a.descripcion like '%REF%');
            if (this.txtArticulos.getText().length() > 0) {
                sql = "select * from articulos a, aplican n WHERE n.ofertasId=" + this.txtOfertas.getText()
                        + " and a.ref=n.articulosRef and (a.ref like '%" + this.txtArticulos.getText()
                        + "%' or a.descripcion like '%" + this.txtArticulos.getText() + "%')";
            } else {
                
                sql = "select * from articulos a, aplican n WHERE n.ofertasId=" + this.txtOfertas.getText() + " and a.ref=n.articulosRef ";
            }
        } else {
            if (this.txtArticulos.getText().length() > 0) {
                sql = "select * from articulos where ref like '%" + this.txtArticulos.getText() + "%' or ref like '%" + this.txtArticulos.getText() + "%'";
            } else {
                sql = "select * from articulos";
            }

        }
        return sql;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtArticulos = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel5 = new javax.swing.JLabel();
        lbCliImg = new javax.swing.JLabel();
        lNombre = new javax.swing.JLabel();
        lCorreoCli = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        btPerfil = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        btPedidos = new javax.swing.JButton();
        btCesto = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btOfertas = new javax.swing.JButton();
        lDescricpcion = new javax.swing.JLabel();
        txtOfertas = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        pnVisor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TPV-GESTION");
        setType(java.awt.Window.Type.POPUP);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Bienvenido");
        jToolBar1.add(jLabel5);

        lbCliImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCliImg.setMaximumSize(new java.awt.Dimension(50, 50));
        lbCliImg.setMinimumSize(new java.awt.Dimension(50, 50));
        lbCliImg.setPreferredSize(new java.awt.Dimension(50, 50));
        jToolBar1.add(lbCliImg);

        lNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lNombre.setText("Ronal Arrayaza Gonzales");
        jToolBar1.add(lNombre);

        lCorreoCli.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lCorreoCli.setForeground(new java.awt.Color(0, 51, 255));
        lCorreoCli.setText("jLabel7");
        jToolBar1.add(lCorreoCli);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator3);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("ADMINISTRATIVO");
        jToolBar1.add(jLabel1);

        btPerfil.setText("PERFIL");
        btPerfil.setFocusable(false);
        btPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPerfil.setMaximumSize(new java.awt.Dimension(160, 45));
        btPerfil.setMinimumSize(new java.awt.Dimension(160, 45));
        btPerfil.setPreferredSize(new java.awt.Dimension(160, 45));
        btPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPerfilActionPerformed(evt);
            }
        });
        jToolBar1.add(btPerfil);
        jToolBar1.add(jSeparator1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("OPERACIONES");
        jLabel2.setToolTipText("OPERACIONES");
        jToolBar1.add(jLabel2);

        btPedidos.setText("PEDIDOS");
        btPedidos.setFocusable(false);
        btPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPedidos.setMaximumSize(new java.awt.Dimension(160, 45));
        btPedidos.setMinimumSize(new java.awt.Dimension(160, 45));
        btPedidos.setPreferredSize(new java.awt.Dimension(160, 45));
        btPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidosActionPerformed(evt);
            }
        });
        jToolBar1.add(btPedidos);

        btCesto.setText("CESTA");
        btCesto.setFocusable(false);
        btCesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCesto.setMaximumSize(new java.awt.Dimension(160, 45));
        btCesto.setMinimumSize(new java.awt.Dimension(160, 45));
        btCesto.setPreferredSize(new java.awt.Dimension(160, 45));
        btCesto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btCesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCestoActionPerformed(evt);
            }
        });
        jToolBar1.add(btCesto);

        btBuscar.setText("Busar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btOfertas.setMaximumSize(new java.awt.Dimension(35, 35));
        btOfertas.setMinimumSize(new java.awt.Dimension(35, 35));
        btOfertas.setPreferredSize(new java.awt.Dimension(35, 35));
        btOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOfertasActionPerformed(evt);
            }
        });

        lDescricpcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        pnVisor.setAutoscrolls(true);
        pnVisor.setMinimumSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout pnVisorLayout = new javax.swing.GroupLayout(pnVisor);
        pnVisor.setLayout(pnVisorLayout);
        pnVisorLayout.setHorizontalGroup(
            pnVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnVisorLayout.setVerticalGroup(
            pnVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        scroll.setViewportView(pnVisor);

        jLabel3.setText("OFERTAS DISPONIBLES:");

        jLabel4.setText("ARTICULOS:");

        jMenu2.setText("File");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem2.setText("Acerca de");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar)
                        .addGap(0, 582, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lDescricpcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDescricpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addComponent(btOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String sql = this.cargarFiltros();
        /*
        [200, 250]
         */
        int xPanel = this.pnVisor.getSize().width;
        int yPanel = this.pnVisor.getSize().height;
        this.pnVisor.removeAll();
        int y = 0;
        int x = 0;
        try {
            ResultSet rs = bd.Consulta(sql);
            while (rs.next()) {
                String refe = rs.getString("ref");
                double dto = 0;
                try {
                    dto = rs.getDouble("descuento");
                } catch (Exception ex) {

                }
                int cantidad = 0;
                try {
                    cantidad = rs.getInt("cantidad");
                } catch (Exception ex) {

                }
                Articulo arti = new Articulo(refe);
                arti.recuperaDatos();
                Muestra muestra = new Muestra(arti, this.cliente.getDni(), dto, cantidad);
                muestra.setSize(200, 250);
                muestra.setLocation(x, y);
                this.pnVisor.add(muestra, BorderLayout.LINE_END);
                this.pnVisor.revalidate();
                this.pnVisor.repaint();
                if ((x + 405) > xPanel) {
                    x = 0;
                    y = y + 255;
                } else {
                    x = x + 205;
                }
            }
            bd.cerrarConexion();
            this.pnVisor.setPreferredSize(new Dimension(xPanel, (y + 255)));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOfertasActionPerformed
        PanelOfertas dialog = new PanelOfertas(true, new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                //System.exit(0);
            }
        });
        dialog.setVisible(true);
        if (dialog.getResult() == JOptionPane.OK_OPTION) {
            this.lDescricpcion.setText(dialog.getOfertas().getNombre());
            this.txtOfertas.setText(String.valueOf(dialog.getOfertas().getId()));
        }
    }//GEN-LAST:event_btOfertasActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        System.out.println("sasdasd");
        this.btBuscarActionPerformed(null);
    }//GEN-LAST:event_formWindowStateChanged

    private void btPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidosActionPerformed
        
         PanelPedido dialog = new PanelPedido(false, this.cliente,new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                       // System.exit(0);
                    }
                });
                dialog.setVisible(true);
    }//GEN-LAST:event_btPedidosActionPerformed

    private void btCestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCestoActionPerformed
       
         PanelCarrito dialog = new PanelCarrito(cliente,new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                dialog.setVisible(true);
    }//GEN-LAST:event_btCestoActionPerformed

    private void btPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPerfilActionPerformed

        frPerfil dialog = new frPerfil(this.cliente, new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                //System.exit(0);
            }
        });
        dialog.setVisible(true);
        this.cargarPerfil();
    }//GEN-LAST:event_btPerfilActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelOfertasCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelOfertasCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelOfertasCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelOfertasCli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                PanelOfertasCli jj = new PanelOfertasCli(new Cliente());
                jj.setVisible(true);
                // jj.setExtendedState(JFrame.MAXIMIZED_BOTH);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCesto;
    private javax.swing.JButton btOfertas;
    private javax.swing.JButton btPedidos;
    private javax.swing.JButton btPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lCorreoCli;
    private javax.swing.JLabel lDescricpcion;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lbCliImg;
    private javax.swing.JPanel pnVisor;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField txtArticulos;
    private javax.swing.JTextField txtOfertas;
    // End of variables declaration//GEN-END:variables
}
