package Pedidos.Interfaces;

import Articulos.Articulo;
import Articulos.PanelArticulos;
import Pedidos.ArticuloPedido;
import Pedidos.Pedido;
import Persona.Cliente;
import bd.bd;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vennuss
 */
public class PanelCrearPedido extends javax.swing.JFrame {
    
    private final Pedido pd = new Pedido();

    /**
     * Creates new form PanelCarrito
     * @param client
     * @param admin
     */
    public PanelCrearPedido() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pd.setFormaPago(jCBPago.getItemAt(jCBPago.getSelectedIndex()));
        jBFin.setEnabled(false);
    }
    
    private void añadirArticulo(Articulo _art, int _cant, int _dto){
        jBFin.setEnabled(true);
        pd.addArticulo(_art, _cant, _dto);
        jTPrecio.setText(String.valueOf(pd.getprecioFinal()));
        refrescar();
    }
    
    private void refrescar(){
        
        DefaultTableModel tm = (DefaultTableModel) this.jTAP.getModel();
        this.jTAP.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        tm.setRowCount(0);
        double PFinal = 0;
        
        for (ArticuloPedido a : pd.getArticulos()) {
            String articulo = a.getArticuloRef();
            int cantidad = a.getCantidad();
            double precioDelArticulo = a.getArticuloPrecio();
            double precioTotal = a.getArticuloPrecio() * a.getCantidad();
            int descuento = a.getDescuento();
            double precioFinal = a.getPrecio();
            
            Object nuev[] = {articulo, cantidad, precioDelArticulo, precioTotal, descuento, precioFinal};
            tm.addRow(nuev);
            PFinal += precioFinal;
        }
        jTPrecio.setText(Double.toString(PFinal));
        if(pd.getArticulos().size() <= 0) jBFin.setEnabled(false);
        else jBFin.setEnabled(true);
    }
    
    private void setCliente(Cliente _client){
        jTDni.setText(_client.getDni());
        jTDni.setText(_client.getNombres() + " " + _client.getApellidos());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAP = new javax.swing.JTable();
        jCBPago = new javax.swing.JComboBox<>();
        jTPrecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBFin = new javax.swing.JButton();
        jBArticulo = new javax.swing.JButton();
        jBCliente = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jTDni = new javax.swing.JLabel();
        jTApellidos = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTAP.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTAP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Articulo", "Cantidad", "Precio del Articulo", "Precio Total", "Descuento", "Precio Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAP.setMinimumSize(new java.awt.Dimension(1100, 800));
        jTAP.setName(""); // NOI18N
        jTAP.setPreferredSize(new java.awt.Dimension(1100, 800));
        jTAP.setRowHeight(40);
        jScrollPane1.setViewportView(jTAP);

        jCBPago.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCBPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Visa", "Credito", "Efectivo" }));
        jCBPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPagoActionPerformed(evt);
            }
        });
        jCBPago.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCBPagoPropertyChange(evt);
            }
        });

        jTPrecio.setEditable(false);
        jTPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPrecioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Precio Final €");

        jBFin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jBFin.setText("Finalizar Pedido");
        jBFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinActionPerformed(evt);
            }
        });

        jBArticulo.setMaximumSize(new java.awt.Dimension(40, 40));
        jBArticulo.setMinimumSize(new java.awt.Dimension(40, 40));
        jBArticulo.setPreferredSize(new java.awt.Dimension(40, 40));
        jBArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBArticuloActionPerformed(evt);
            }
        });

        jBCliente.setMaximumSize(new java.awt.Dimension(40, 40));
        jBCliente.setMinimumSize(new java.awt.Dimension(40, 40));
        jBCliente.setPreferredSize(new java.awt.Dimension(40, 40));
        jBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClienteActionPerformed(evt);
            }
        });

        jBBorrar.setMaximumSize(new java.awt.Dimension(40, 40));
        jBBorrar.setMinimumSize(new java.awt.Dimension(40, 40));
        jBBorrar.setPreferredSize(new java.awt.Dimension(40, 40));

        jTDni.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTDni.setText("12345678X");

        jTApellidos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTApellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCBPago, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTDni)
                        .addGap(18, 18, 18)
                        .addComponent(jTApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTDni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPrecio)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBFin, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPagoActionPerformed
        pd.setFormaPago(jCBPago.getItemAt(jCBPago.getSelectedIndex()));
    }//GEN-LAST:event_jCBPagoActionPerformed

    private void jCBPagoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCBPagoPropertyChange
        
    }//GEN-LAST:event_jCBPagoPropertyChange

    private void jTPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPrecioActionPerformed
        
    }//GEN-LAST:event_jTPrecioActionPerformed

    private void jBFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinActionPerformed
        pd.registrar();
        this.dispose();
    }//GEN-LAST:event_jBFinActionPerformed

    private void jBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClienteActionPerformed
       
    }//GEN-LAST:event_jBClienteActionPerformed

    private void jBArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBArticuloActionPerformed
        
        PanelArticulos dialog = new PanelArticulos(true, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                    }
                });
                dialog.setVisible(true);
                if(dialog.getResult() == JOptionPane.OK_OPTION){
                pd.addArticulo(dialog.getArticulo(), 1, 0);
                }
    }//GEN-LAST:event_jBArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelCrearPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelCrearPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelCrearPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCrearPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelCrearPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBArticulo;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBCliente;
    private javax.swing.JButton jBFin;
    private javax.swing.JComboBox<String> jCBPago;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAP;
    private javax.swing.JLabel jTApellidos;
    private javax.swing.JLabel jTDni;
    private javax.swing.JTextField jTPrecio;
    // End of variables declaration//GEN-END:variables
}
